{% set python_min = python_min|default("0.1a0") %}
{% set name = "django-currentuser" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_currentuser-{{ version }}.tar.gz
  sha256: 3805fe2ef2a85456c6b791417e0bf782e62c8d8fa021c280d96624b1e942e504

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=61.0.0
    - setuptools-scm >=5.0.0
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2,<6.0

test:
  imports:
    - django_currentuser
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/zsoldosp/django-currentuser
  summary: Conveniently store reference to request user on thread/db level.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gscoppino
    - alexpilot11
